security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: ROLE_ADMIN

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

# pour auth


        api:
                    pattern:    ^/api
                    fos_oauth:  true
                    stateless:  true
                    anonymous:  false #
        oauth_token:
            pattern:    ^/oauth/v2/token
            security:   false
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                login_path: /login
                check_path: /login_check

            logout:
              path: /logout
              target: /
            logout:       true
            anonymous:    true
        oauth_authorize:
              pattern:    ^/oauth/v2/auth
#              form_login:
#                   provider: fos_userbundle
#                   check_path: /login_check
#                   login_path: /login
              anonymous: true
    access_control:
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
       # - { path: ^/api,  role: IS_AUTHENTICATED_FULLY }
        - { path: ^/,  role: IS_AUTHENTICATED_FULLY }