# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
#    service_name:
#        class: AppBundle\Directory\ClassName
#        arguments: ["@another_service_name", "plain_value", "%parameter_name%"]
     app.service_stripe:
            class:     ApiBundle\Service\StripeService
            arguments: ['%URL_API%']

     api.service.manager.stripe:
            class:    ApiBundle\Manager\ClientStripe
            arguments: ['@doctrine.orm.entity_manager','@app.service_stripe']