<?php

namespace ApiBundle\Repository;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllProduit()
    {
        $qb = $this->createQueryBuilder("p")
            ->select('p.id,p.name,p.prix');
        return $qb->getQuery()->getResult();
    }
}
